export const SEARCHED_USERS = 'SEARCHED_USERS';
export const SEARCHED_USERS_FAILED = 'SEARCHED_USERS_FAILED';
export const RECEIVED_USERS = 'RECEIVED_USERS';
export const CLEARED_RESULTS = 'CLEARED_RESULTS';

export const REQUESTED_USER_REPOS = 'REQUESTED_USER_REPOS';
export const REQUESTED_USER_REPOS_FAILED = 'REQUESTED_USER_REPOS_FAILED';
export const RECEIVED_USER_REPOS = 'RECEIVED_USER_REPOS';
