export const SEARCHED_USERS = 'SEARCHED_USERS';
export const RECEIVED_USERS = 'RECEIVED_USERS';
export const CLEARED_SEARCH_RESULTS = 'CLEARED_SEARCH_RESULTS';

export const REQUESTED_USER_REPOS = 'REQUESTED_USER_REPOS';
export const RECEIVED_USER_REPOS = 'RECEIVED_USER_REPOS';

export const CHECKED_ADMIN_ACCESS = 'CHECKED_ADMIN_ACCESS';
export const ACCESS_DENIED = 'ACCESS_DENIED';
